/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as Startseite3RouteImport } from './routes/startseite3'
import { Route as Startseite2RouteImport } from './routes/startseite2'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const Startseite3Route = Startseite3RouteImport.update({
  id: '/startseite3',
  path: '/startseite3',
  getParentRoute: () => rootRouteImport,
} as any)
const Startseite2Route = Startseite2RouteImport.update({
  id: '/startseite2',
  path: '/startseite2',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startseite2': typeof Startseite2Route
  '/startseite3': typeof Startseite3Route
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startseite2': typeof Startseite2Route
  '/startseite3': typeof Startseite3Route
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/referenzen': typeof ReferenzenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/startseite2': typeof Startseite2Route
  '/startseite3': typeof Startseite3Route
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/sitemap.xml'
    | '/startseite2'
    | '/startseite3'
    | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/sitemap.xml'
    | '/startseite2'
    | '/startseite3'
    | '/ueber-uns'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/leistungen'
    | '/referenzen'
    | '/sitemap.xml'
    | '/startseite2'
    | '/startseite3'
    | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  ReferenzenRoute: typeof ReferenzenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Startseite2Route: typeof Startseite2Route
  Startseite3Route: typeof Startseite3Route
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startseite3': {
      id: '/startseite3'
      path: '/startseite3'
      fullPath: '/startseite3'
      preLoaderRoute: typeof Startseite3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startseite2': {
      id: '/startseite2'
      path: '/startseite2'
      fullPath: '/startseite2'
      preLoaderRoute: typeof Startseite2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  ReferenzenRoute: ReferenzenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Startseite2Route: Startseite2Route,
  Startseite3Route: Startseite3Route,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
